# Generated by Django 5.2.12 on 2026-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Number of simultaneous appointments allowed'),
        ),
        migrations.AddField(
            model_name='business',
            name='close_time',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='business',
            name='open_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
