# Generated by Django 5.2.12 on 2026-03-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_capacity_business_close_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='capacity',
        ),
    ]
