# Generated by Django 5.2.12 on 2026-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_remove_business_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='map_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
