# Generated by Django 5.2.12 on 2026-03-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Number of staff or stations available for this specific service'),
        ),
    ]
